# Generated by Django 2.0.4 on 2018-05-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180425_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('parent_org', 'name')},
        ),
    ]
