# Generated by Django 2.0.4 on 2018-05-22 09:01

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.TextField(max_length=1000)),
                ('answer_body', models.TextField(max_length=1000)),
                ('level', models.IntegerField(choices=[(1, 'Level 100'), (2, 'Level 200'), (3, 'Level 300'), (4, 'Level 400')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('created_at', 'level'),
            },
        ),
    ]
