# Generated by Django 2.0.4 on 2018-05-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 100'), (2, 'Level 200'), (3, 'Level 300')]),
        ),
    ]
