# Generated by Django 2.0.4 on 2018-05-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20180523_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(choices=[(1, 'Junior'), (2, 'Senior'), (3, 'Advanced')]),
        ),
    ]
