# Generated by Django 2.0.4 on 2018-06-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20180523_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_body',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=models.TextField(max_length=2000),
        ),
    ]
